{
    'name': 'Sunat T-Registro',
    'version': '16.0.0.0.0',
    'author': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'description': "This module outputs the files for bulk loading of the t-registro",
    'summary': "This module outputs the files for bulk loading of the t-registro",
    'depends': [
        'account',
        'l10n_pe_edi',
        'hr',
        'personal_information',
        'eps_process',
        'payment_conditions',
        'additional_fields_payroll',
    ],
    'data': [
        'data/international.industrial.classification.csv',
        'data/ubigeo.reniec.object.csv',
        'data/occupational.worker.category.csv',
        'data/worker.type.pensioner.provider.csv',
        'data/type.formative.modality.work.csv',
        'data/occupation.work.personnel.training.modality.csv',
        'data/zone.type.object.csv',
        'data/road.type.object.csv',
        'data/edu.career.object.csv',
        'data/edu.name.object.csv',
        'data/edu.year.graduation.object.csv',
        'data/res_country.xml',
        'security/ir.model.access.csv',
        'views/base_views.xml',
        'views/t_registro_views.xml',
        'views/personal_views.xml',
        'views/right_holders_views.xml',
        'views/relatives_extra_information.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'Other proprietary',
    'currency': 'USD',
    'price': 0.00
}
